import type { NextPage } from 'next'
import Head from 'next/head'
import Slider from '../src/Slider'
import { CardProps } from '../src/Card/types'
import Card from '../src/Card'
import styled from 'styled-components'
// @ts-ignore
import 'intersection-observer'

import accessoriesImage from '../public/assets/accessories.jpeg'
import basketballImage from '../public/assets/basketball.jpeg'
import golfImage from '../public/assets/golf.jpeg'
import ivyImage from '../public/assets/ivy.jpeg'
import legacyImage from '../public/assets/legacy.jpeg'
import runningImage from '../public/assets/running.jpeg'
import BigSection from '../src/BigSection'
import Header from '../src/Header'
import Footer from '../src/Footer'
import TextSection from '../src/TextSection'

const CARDS_DATA: CardProps[] = [
  {
    title: 'Accessories',
    href: '/accessories',
    media: { resource_type: 'image', ...accessoriesImage }
  },
  {
    title: 'Basketball',
    href: '/basketball',
    media: { resource_type: 'image', ...basketballImage }
  },
  {
    title: 'Golf',
    href: '/golf',
    media: { resource_type: 'image', ...golfImage }
  },
  {
    title: 'Winter',
    href: '/winter',
    media: { resource_type: 'video', src: '/assets/winter2.mp4', width: 524, height: 700, format: 'mp4' }
  },
  {
    title: 'ADIDAS X IVY PARK',
    href: '/adidas-x-ivy-park',
    media: { resource_type: 'image', ...ivyImage }
  },
  {
    title: 'Living Legacy',
    href: '/living-legacy',
    media: { resource_type: 'image', ...legacyImage }
  },
  {
    title: 'Running',
    href: '/running',
    media: { resource_type: 'image', ...runningImage }
  },
  {
    title: 'Ultraboost',
    href: '/ultraboost',
    media: { resource_type: 'video', src: '/assets/ultra.mp4', width: 524, height: 700, format: 'mp4' }
  }
]

const Main = styled.div`
  position: relative;
  display: grid;
  grid-gap: 100px;
  width: 100%;
`

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <BigSection />
        <TextSection />
        <Slider title={'Adidas Collections'}>
          {CARDS_DATA.map((card) => (
            <Card {...card} key={card.title} />
          ))}
        </Slider>
        <TextSection />
        <Footer />
      </Main>
    </>
  )
}

export default Home
